# import libraries

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
import sklearn

# import dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path = '/content/drive/MyDrive/Learning/data analysis/projects/profile project/dataset/Salary_Data.csv'
df = pd.read_csv(path)
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

# process and prepare

## check data types

In [ ]:
df.dtypes

YearsExperience    float64
Salary             float64
dtype: object

## check Null values

In [ ]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

## check of duplicated values

In [ ]:
df.duplicated().sum()

0

## check data validity

In [ ]:
df['YearsExperience'].unique()

array([ 1.1,  1.3,  1.5,  2. ,  2.2,  2.9,  3. ,  3.2,  3.7,  3.9,  4. ,
        4.1,  4.5,  4.9,  5.1,  5.3,  5.9,  6. ,  6.8,  7.1,  7.9,  8.2,
        8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [ ]:
df['Salary'].unique()

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [ ]:
df.describe().round(2)

YearsExperience     Salary
count            30.00      30.00
mean              5.31   76003.00
std               2.84   27414.43
min               1.10   37731.00
25%               3.20   56720.75
50%               4.70   65237.00
75%               7.70  100544.75
max              10.50  122391.00

## check outliers

In [ ]:
px.box(data_frame=df.melt(),color='variable',points='all',facet_col='variable').update_yaxes(matches=None)

# analysis

In [ ]:
px.histogram(data_frame=df,x='YearsExperience',y='Salary',height=400)

In [ ]:
px.scatter(data_frame=df,x='YearsExperience',y='Salary',trendline='ols',height=400)

# equation
- **y = mX + b**

# train \ test split dataset

In [ ]:
df.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [ ]:
y = df['Salary']
X = df.drop(columns= 'Salary',axis=1)

In [ ]:
y

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

In [ ]:
X

YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape

(24, 1)

In [ ]:
X_test.shape

(6, 1)

In [ ]:
y_train.shape

(24,)

In [ ]:
y_test.shape

(6,)

# model building

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.predict(X_test)

array([115790.21011287,  71498.27809463, 102596.86866063,  75267.80422384,
        55477.79204548,  60189.69970699])

# model evaluation

In [ ]:
model.score(X_train,y_train)

0.9645401573418146